The main logic of entities is written
ekip-s/java-filmorate pull request #1
Opened 2022-07-10 13:55 UTC by ekip-s

Написал основную логику сущностей, и взаимодействия с ними + тесты

2022-07-10 19:44 UTC, Fleaman777 requested changes

2022-07-10 19:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +        return filmId;
На 1 строчку можно сократить код, если написать:
return ++filmId;

2022-07-10 19:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controllers/UserController.java
> +        }
Хорошо что на каждый тип ошибки выводишь своё сообщение

2022-07-10 19:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
ValidationException можно наследовать от ResponseStatusException,
и потом использовать конструктор:

public ValidationException(HttpStatus status, String massage) {
super(status, massage);
}

где status какой-нибудь соответсвующий ошибке Http статус

2022-07-10 19:44 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controllers/UserController.java
> +    private void validation(User user) {
Молодец, что валидацию вынес в отдельный метод,

но более правильный подход тогда, когда контроллер только принимает запросы и отдает респонсы, а всю остальную логику выполняют другие классы(сервисы)

это не считается ошибкой,
выносить этот метод в отдельный класс или нет остается за тобой :)

аналагично и в фильм контроллере

2022-07-10 19:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/controllers/FilmValidationTest.java
> +    void createTestSpase() {
Отличное использование @BeforeEach аннотации

2022-07-10 19:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/controllers/FilmValidationTest.java
> +        }
В целом, в тестах можно не отлавливать исключения, т. к. если оно вылетает в тот момент когда исключение не тестируется, то значит в приложении какие-то проблемы, и их нужно фиксить. 
поэтому можно просто или прописывать в сигнатуре тест метода, исключения которые выбрасываются, или использовать специальную ломбок аннотацию

2022-07-10 19:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/controllers/FilmValidationTest.java
> +    void validationFilmTest() {
Лучше на каждый эндпоинт делать свои тест методы, так легче поддерживать тесты, и по тестам будет проще понять, что происходит в приложении. 

Причём по хорошему, каждый эндпоинт нужно тестировать и в успешных и неуспешных кейсах

(но т. к. ты итак сделал больше чем требуется в задании, то успешные кейсы пока тестировать необязательно :)

2022-07-10 19:44 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/controllers/UserValidationTest.java
> +    public static class LocalDateAdapter extends TypeAdapter<LocalDate> {
Этот класс можно было бы вынести в утилиты тестов

2022-07-12 13:13 UTC, ekip-s commented on src/main/java/ru/yandex/practicum/controllers/UserController.java
> +    private void validation(User user) {
Я сделал, пока так, в спринтах далее как понимаю будут более подходящие для этого классы, а сейчас решил не выносить эту логику.

2022-07-12 13:20 UTC, ekip-s commented on src/test/java/ru/yandex/practicum/controllers/FilmValidationTest.java
> +    void validationFilmTest() {
В задании тесты, только по валидации вроде  как нужны - а она и для создания и для обновления одна - поэтому сделал один тест на все;

2022-07-13 16:02 UTC, Fleaman777 commented on src/test/java/ru/yandex/practicum/controllers/FilmValidationTest.java
> +    void validationFilmTest() {
валидация хоть и одна, но кейсов, когда она может не пройти, и соответственно приложение упадет, несколько, 
каждый такой случай нужно выносить в отдельный тест-метод

2022-07-14 11:55 UTC, Fleaman777 requested changes

2022-07-14 11:55 UTC, Fleaman777 commented on src/main/java/ru/yandex/practicum/controllers/FilmController.java
> +    public ArrayList<Film> get() {
лучше использовать более широкий тип List

2022-07-15 13:07 UTC, merged